mathproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    
    path('', include('yahoodata.urls')),
    path('admin/', admin.site.urls),
]

yahoodata/urls.py
from django.urls import path

from . import views

app_name = 'yahoodata'

urlpatterns = [
    path('', views.index, name='index'),
    path('csv', views.csv, name='csv'),
    path('getData',views.getdata, name='getData')
]

yahoodata/models.py
from django.db import models

class Prediccion(models.Model):
    accion = models.CharField(max_length=100)
    fecha = models.DateTimeField('fecha')
    precio_real = models.DecimalField(max_digits=20,decimal_places=10)
    precio_estimado = models.DecimalField(max_digits=20,decimal_places=10)

yahoodata/views.py
from django.shortcuts import render
from django.contrib import messages

from django.http import HttpResponse, HttpResponseNotFound, Http404,  HttpResponseRedirect

from datetime import date, datetime
import rpy2
import rpy2.robjects as robjects
import numpy as np
from yahoo_quote_download import yqd
import json

from django.utils import timezone

# quandl for financial data
import quandl
# pandas for data manipulation
import pandas as pd
quandl.ApiConfig.api_key = '-gzDw8tzAHNQZzxp8YXX'


from .models import Prediccion



# Create your views here.

from django.http import HttpResponse


def index(request):
    return render(request, 'yahoodata/index.html', {
       "last_action": Prediccion.objects.latest('id').accion,
        "precio_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_real),
        "estimado_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_estimado)})

def csv(request):
    return render(request, 'yahoodata/csv.html', {
        "last_action": Prediccion.objects.latest('id').accion,
        "precio_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_real),
        "estimado_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_estimado)
        })

def getdata(request):
    req = request.POST
    fecha_inicio = "2017-01-01"
    

    today = str(date.today())
    fecha_fin = '-'.join(today.split('-'))

    codigo = req.get("codigo")
    print(req)
    
    
    if (req.get("automatico") == "0"):
        print("manual")
        csv = request.FILES['csv']
        historical_data_raw = pd.read_csv(csv)
        adj = []
        adj = historical_data_raw['Adj Close'].values.tolist()
    
    else:
        print("automatico")
        try:
            historical_data_raw = quandl.get('WIKI/'+ codigo,  start_date=fecha_inicio, end_date=fecha_fin)
            adj = []
            adj = historical_data_raw['Adj. Close'].values.tolist()
        except:
            print("No Existe")
            messages.warning(request, 'El código '+codigo+' no es un código válido. Intente nuevamente')
            return HttpResponseRedirect("/")
    

    adj = [float(i) for i in adj]
    compra= datetime.strptime(req.get("fecha_compra"), '%Y-%m-%d').date()
    hoy=date.today()    
    Tm = compra - hoy
    Tm=Tm.days/365.
    S = adj[-1]
    k = np.mean(adj)
    sigma = np.std(adj)

    M = int(req.get("puntos"))
    #M=1000

    n_trayectorias = int(req.get("trayectorias"))
    put = int(req.get("tipo") == "Compra")

    r=float(req.get("tasa_interes"))/100.
    print("S= ",S)
    print("k= ",k)
    print("Tm= ",Tm)
    print("r= ",r)
    print("sigma= ",sigma)
    print("M= ",M)
    print("put= ",put)
    r_f = robjects.r('''black_scholes <- function(S, k, Tm, r, sigma){
        values <- c(1)
        d1 <- (log(S/k) + (r+(sigma^2)/2)*(Tm))/(sigma*sqrt(Tm))
        d2 <- (log(S/k) + (r-(sigma^2)/2)*(Tm))/(sigma*sqrt(Tm))
        
        values[1] <- S*pnorm(d1) - k*exp(-r*Tm)*pnorm(d2)
        values[2] <- k*exp(-r*Tm)*pnorm(-d2)- S*pnorm(-d1)

        values
    }''')

    res= r_f(S,k,Tm,r,sigma)

    montecarlo = robjects.r('''montecarlo_black_scholes <- function(S, k, Tm, r,sigma, M,put){
        cat(S)
        values <- matrix(nrow=M,ncol=2)
        var <- 0
        I_0 <- 0
        if(put == 1){
            I_1 <- max( k - S*exp((r-(sigma^2)/2)*Tm + sigma*sqrt(Tm)*rnorm(1, 0, 1)),0)
        }else{
            I_1 <- max( -k + S*exp((r-(sigma^2)/2)*Tm + sigma*sqrt(Tm)*rnorm(1, 0, 1)),0)
        }
        

        values[1,1] <- 1
        values[1,2] <- I_1


        
        for(i in 2:M){
            if(put == 1){
                h_i <- max( k - S*exp((r-(sigma^2)/2)*Tm + sigma*sqrt(Tm)*rnorm(1, 0, 1)),0)
            }else{
                h_i <- max( -k + S*exp((r-(sigma^2)/2)*Tm + sigma*sqrt(Tm)*rnorm(1, 0, 1)),0)
            }
            I_1 <- I_1 + (h_i -  I_1)/(i+1)
            values[i,1] <- i
            values[i,2] <- I_1
        } 

        values
    }''')

    trayectorias = list()
    valores_finales = list()

    
    for i in range(n_trayectorias):
        montecarlo_res = montecarlo(S,k,Tm,r,sigma,M,put)
        montecarlo_res = (np.asarray(montecarlo_res))
        montecarlo_res_x = montecarlo_res[:,0].tolist()
        montecarlo_res_y = montecarlo_res[:,1].tolist()

        valor_final = float(montecarlo_res_y[-1])

        montecarlo_res_x = json.dumps(montecarlo_res_x)
        montecarlo_res_y = json.dumps(montecarlo_res_y)

        trayectorias.append(montecarlo_res_y)
        valores_finales.append(valor_final)


        print("Listo: ", valor_final)

    compra=res[0]
    venta=res[1]

    trayectorias = json.dumps(trayectorias)
    valores_finales = np.array(valores_finales)

    
    #guardar en bd

    

    
    if req.get("tipo")=="Compra":

        prediccion = Prediccion(accion=codigo, fecha=timezone.now(), precio_real=compra, precio_estimado=np.mean(valores_finales))
        prediccion.save()

        context = {"data_x": montecarlo_res_x,"data_y": trayectorias, "cantidad_puntos": M, "cantidad_trayectorias": n_trayectorias,
        "accion": codigo, "resultado": compra,"tipo": "comprar", "fecha":req.get("fecha_compra"),
        "valor_final_montecarlo": np.mean(valores_finales), "error": np.mean(valores_finales) - float(compra),
        "desviacion_valores_finales": np.std(valores_finales),

       "last_action": Prediccion.objects.latest('id').accion,
        "precio_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_real),
        "estimado_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_estimado),
        }
    else:

        prediccion = Prediccion(accion=codigo, fecha=timezone.now(), precio_real=venta, precio_estimado=np.mean(valores_finales))
        prediccion.save()

        context = {"data_x": montecarlo_res_x,"data_y": trayectorias, "cantidad_puntos": M,"cantidad_trayectorias": n_trayectorias,
        "accion": codigo, "resultado": venta, "tipo": "vender", "fecha":req.get("fecha_compra"),
        "valor_final_montecarlo": np.mean(valores_finales), "error": np.mean(valores_finales) - float(venta),
        "desviacion_valores_finales": np.std(valores_finales),

       "last_action": Prediccion.objects.latest('id').accion,
        "precio_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_real),
        "estimado_last_action": "{0:.2f}".format(Prediccion.objects.latest('id').precio_estimado),
        }
    return render(request,'yahoodata/viewResults.html',context)

yahoodata/templates/yahoodata/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static%}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href= "/static/assets/images/fondo_praderas.png">
    <title>MathProject</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet">
    <!-- Page plugins css -->
    <link href="{% static 'assets/plugins/clockpicker/dist/jquery-clockpicker.min.css' %}" rel="stylesheet">
    <!-- Color picker plugins css -->
    <link href="{% static 'assets/plugins/jquery-asColorPicker-master/css/asColorPicker.css' %}" rel="stylesheet">
    <!-- Date picker plugins css -->
    <link href="{% static 'assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Daterange picker plugins css -->
    <link href="{% static 'assets/plugins/timepicker/bootstrap-timepicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static 'css/colors/default-dark.css' %}" id="theme" rel="stylesheet">


    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js' %}"></script>
<![endif]-->
</head>
  <body>
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->

            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <!-- Card -->
                    <div class="card">
                            
                        <div class="card-body">

                                {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                    <li{% if message.tags %} class="alert alert-danger"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                                
                            <h4 class="card-title">Elegir fechas y Accion</h4>
                            <h6 class="card-subtitle">Elija fechas y nombre de acción</h6>
                            <form action="{% url 'yahoodata:getData' %}" method="POST">
                            <div class="row form-material">

                                   

                                <div class="col-md-12">

                                    <label class="m-t-40">Código Accion</label>
                                    <input type="text" required class="form-control" name="codigo" placeholder="Escriba Código Acción">
                                </div>

                                <div class="col-md-12">

                                    <label class="m-t-40">Tipo Opción</label>

                                    <select name="tipo" required class="form-control form-control-line">
                                      <option name="compra"> Compra </option>
                                      <option name="venta"> Venta </option>
                                    </select>
                                </div>

                                <div class="col-md-12">
                                    <label class="m-t-20">Fecha Compra Acción</label>
                                    <input type="text" class="form-control mdate" required name = "fecha_compra" >

                                </div>

                                <div class="col-md-12">

                                    <label class="m-t-40">Porcentaje de Interés libre de riesgo</label>
                                    <input type="number" class="form-control" name="tasa_interes" required pattern="[0-9]{1,3}" placeholder="Escriba porcentaje (de 1 a 100)">
                                </div>

                                <div class="col-md-12">
                                    <label class="m-t-40">Cantidad de Trayectorias</label>
                                    <input type="number" class="form-control" name="trayectorias" required  placeholder="Escriba cantidad (No muy grande)">
                                </div>

                                <div class="col-md-12">
                                    <label class="m-t-40">Cantidad de Puntos por trayectoria</label>
                                    <input type="number" class="form-control" name="puntos" required  placeholder="Escriba cantidad">
                                </div>



                                {% csrf_token %}

                                <button class="btn btn-success" type="submit"> Enviar </button>
                              </form>

                              
                            </div>
                        </div>
                    </div>


                </div>
            </div>
            <!-- ============================================================== -->

            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer"> mathproject </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>

    <script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'js/jquery.slimscroll.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'js/sidebarmenu.js' %}"></script>
    <!--stickey kit -->
    <script src="{% static 'assets/plugins/sticky-kit-master/dist/sticky-kit.min.js' %}"></script>
    <script src="{% static 'assets/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'js/custom.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- Plugins for this page -->
    <!-- ============================================================== -->
    <!-- Plugin JavaScript -->
    <script src="{% static 'assets/plugins/moment/moment.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
    <!-- Clock Plugin JavaScript -->
    <script src="{% static 'assets/plugins/clockpicker/dist/jquery-clockpicker.min.js' %}"></script>
    <!-- Color Picker Plugin JavaScript -->
    <script src="{% static 'assets/plugins/jquery-asColorPicker-master/libs/jquery-asColor.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-asColorPicker-master/libs/jquery-asGradient.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js' %}"></script>
    <!-- Date Picker Plugin JavaScript -->
    <script src="{% static 'assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <!-- Date range Plugin JavaScript -->
    <script src="{% static 'assets/plugins/timepicker/bootstrap-timepicker.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <script>
    // MAterial Date picker
    $('.mdate').bootstrapMaterialDatePicker({
        weekStart: 0,
        time: false
    });
    $('#timepicker').bootstrapMaterialDatePicker({
        format: 'HH:mm',
        time: true,
        date: false
    });
    $('#date-format').bootstrapMaterialDatePicker({
        format: 'dddd DD MMMM YYYY - HH:mm'
    });

    $('#min-date').bootstrapMaterialDatePicker({
        format: 'DD/MM/YYYY HH:mm',
        minDate: new Date()
    });
    // Clock pickers
    $('#single-input').clockpicker({
        placement: 'bottom',
        align: 'left',
        autoclose: true,
        'default': 'now'
    });
    $('.clockpicker').clockpicker({
        donetext: 'Done',
    }).find('input').change(function() {
        console.log(this.value);
    });
    $('#check-minutes').click(function(e) {
        // Have to stop propagation here
        e.stopPropagation();
        input.clockpicker('show').clockpicker('toggleView', 'minutes');
    });
    if (/mobile/i.test(navigator.userAgent)) {
        $('input').prop('readOnly', true);
    }
    // Colorpicker
    $(".colorpicker").asColorPicker();
    $(".complex-colorpicker").asColorPicker({
        mode: 'complex'
    });
    $(".gradient-colorpicker").asColorPicker({
        mode: 'gradient'
    });
    // Date Picker
    jQuery('.mydatepicker, #datepicker').datepicker();
    jQuery('#datepicker-autoclose').datepicker({
        autoclose: true,
        todayHighlight: true
    });
    jQuery('#date-range').datepicker({
        toggleActive: true
    });
    jQuery('#datepicker-inline').datepicker({
        todayHighlight: true
    });
    // Daterange picker
    $('.input-daterange-datepicker').daterangepicker({
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-danger',
        cancelClass: 'btn-inverse'
    });
    $('.input-daterange-timepicker').daterangepicker({
        timePicker: true,
        format: 'MM/DD/YYYY h:mm A',
        timePickerIncrement: 30,
        timePicker12Hour: true,
        timePickerSeconds: false,
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-danger',
        cancelClass: 'btn-inverse'
    });
    $('.input-limit-datepicker').daterangepicker({
        format: 'MM/DD/YYYY',
        minDate: '06/01/2015',
        maxDate: '06/30/2015',
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-danger',
        cancelClass: 'btn-inverse',
        dateLimit: {
            days: 6
        }
    });




    </script>


  </body>
</html>